spring:
  application:
    name: /case
  main:
    banner-mode: 'OFF'
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
#  flyway:
#    enabled: false
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
logging:
  level:
    ROOT: ${LOGGING_LEVEL_ROOT:INFO}
    br:
      com:
        case: ${LOGGING_CASE:DEBUG}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
springdoc:
  api-docs:
    path: /openapi
